/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Branch { 'id' : bigint, 'name' : string }
export type ExternalBlob = Uint8Array;
export interface MCQ {
  'id' : bigint,
  'question' : string,
  'explanation' : [] | [string],
  'correctAnswer' : bigint,
  'subjectId' : bigint,
  'options' : Array<string>,
}
export interface MCQAnswer { 'mcqId' : bigint, 'selectedAnswer' : bigint }
export interface MCQPracticeResult {
  'score' : number,
  'totalQuestions' : bigint,
  'correctAnswers' : bigint,
}
export interface Notes {
  'id' : bigint,
  'title' : string,
  'file' : ExternalBlob,
  'tags' : Array<string>,
  'year' : bigint,
  'subjectId' : bigint,
}
export interface QuestionPaper {
  'id' : bigint,
  'file' : ExternalBlob,
  'year' : bigint,
  'subjectId' : bigint,
  'examType' : [] | [string],
}
export interface SearchResult {
  'questionPapers' : Array<QuestionPaper>,
  'subjects' : Array<Subject>,
  'mcqs' : Array<MCQ>,
  'notes' : Array<Notes>,
}
export interface Semester {
  'id' : bigint,
  'number' : bigint,
  'branchId' : bigint,
}
export interface Subject {
  'id' : bigint,
  'name' : string,
  'semesterId' : bigint,
  'branchId' : bigint,
}
export interface Syllabus { 'overview' : string, 'subjectId' : bigint }
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBranch' : ActorMethod<[string], bigint>,
  'addMCQ' : ActorMethod<
    [bigint, string, Array<string>, bigint, [] | [string]],
    bigint
  >,
  'addNotes' : ActorMethod<
    [bigint, string, bigint, Array<string>, ExternalBlob],
    bigint
  >,
  'addQuestionPaper' : ActorMethod<
    [bigint, bigint, [] | [string], ExternalBlob],
    bigint
  >,
  'addSemester' : ActorMethod<[bigint, bigint], bigint>,
  'addSubject' : ActorMethod<[bigint, bigint, string], bigint>,
  'addSyllabus' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBranch' : ActorMethod<[bigint], undefined>,
  'deleteMCQ' : ActorMethod<[bigint], undefined>,
  'deleteNotes' : ActorMethod<[bigint], undefined>,
  'deleteQuestionPaper' : ActorMethod<[bigint], undefined>,
  'deleteSemester' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'deleteSyllabus' : ActorMethod<[bigint], undefined>,
  'evaluateMCQAnswers' : ActorMethod<[Array<MCQAnswer>], MCQPracticeResult>,
  'getBranch' : ActorMethod<[bigint], [] | [Branch]>,
  'getBranches' : ActorMethod<[], Array<Branch>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMCQById' : ActorMethod<[bigint], [] | [MCQ]>,
  'getMCQsBySubject' : ActorMethod<[bigint], Array<MCQ>>,
  'getNotesById' : ActorMethod<[bigint], [] | [Notes]>,
  'getNotesBySubject' : ActorMethod<[bigint], Array<Notes>>,
  'getQuestionPaperById' : ActorMethod<[bigint], [] | [QuestionPaper]>,
  'getQuestionPapersBySubject' : ActorMethod<[bigint], Array<QuestionPaper>>,
  'getSemesters' : ActorMethod<[], Array<Semester>>,
  'getSemestersByBranch' : ActorMethod<[bigint], Array<Semester>>,
  'getSubject' : ActorMethod<[bigint], [] | [Subject]>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getSubjectsBySemester' : ActorMethod<[bigint], Array<Subject>>,
  'getSyllabusBySubject' : ActorMethod<[bigint], [] | [Syllabus]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'search' : ActorMethod<[string], SearchResult>,
  'updateBranch' : ActorMethod<[bigint, string], undefined>,
  'updateMCQ' : ActorMethod<
    [bigint, bigint, string, Array<string>, bigint, [] | [string]],
    undefined
  >,
  'updateNotes' : ActorMethod<
    [bigint, bigint, string, bigint, Array<string>, ExternalBlob],
    undefined
  >,
  'updateQuestionPaper' : ActorMethod<
    [bigint, bigint, bigint, [] | [string], ExternalBlob],
    undefined
  >,
  'updateSemester' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'updateSubject' : ActorMethod<[bigint, bigint, bigint, string], undefined>,
  'updateSyllabus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];