/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MCQAnswer = IDL.Record({
  'mcqId' : IDL.Nat,
  'selectedAnswer' : IDL.Nat,
});
export const MCQPracticeResult = IDL.Record({
  'score' : IDL.Float64,
  'totalQuestions' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
});
export const Branch = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const MCQ = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'explanation' : IDL.Opt(IDL.Text),
  'correctAnswer' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Notes = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'year' : IDL.Nat,
  'subjectId' : IDL.Nat,
});
export const QuestionPaper = IDL.Record({
  'id' : IDL.Nat,
  'file' : ExternalBlob,
  'year' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'examType' : IDL.Opt(IDL.Text),
});
export const Semester = IDL.Record({
  'id' : IDL.Nat,
  'number' : IDL.Nat,
  'branchId' : IDL.Nat,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'semesterId' : IDL.Nat,
  'branchId' : IDL.Nat,
});
export const Syllabus = IDL.Record({
  'overview' : IDL.Text,
  'subjectId' : IDL.Nat,
});
export const SearchResult = IDL.Record({
  'questionPapers' : IDL.Vec(QuestionPaper),
  'subjects' : IDL.Vec(Subject),
  'mcqs' : IDL.Vec(MCQ),
  'notes' : IDL.Vec(Notes),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBranch' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addMCQ' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addNotes' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'addQuestionPaper' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text), ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'addSemester' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'addSubject' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addSyllabus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBranch' : IDL.Func([IDL.Nat], [], []),
  'deleteMCQ' : IDL.Func([IDL.Nat], [], []),
  'deleteNotes' : IDL.Func([IDL.Nat], [], []),
  'deleteQuestionPaper' : IDL.Func([IDL.Nat], [], []),
  'deleteSemester' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'deleteSyllabus' : IDL.Func([IDL.Nat], [], []),
  'evaluateMCQAnswers' : IDL.Func(
      [IDL.Vec(MCQAnswer)],
      [MCQPracticeResult],
      ['query'],
    ),
  'getBranch' : IDL.Func([IDL.Nat], [IDL.Opt(Branch)], ['query']),
  'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMCQById' : IDL.Func([IDL.Nat], [IDL.Opt(MCQ)], ['query']),
  'getMCQsBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(MCQ)], ['query']),
  'getNotesById' : IDL.Func([IDL.Nat], [IDL.Opt(Notes)], ['query']),
  'getNotesBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Notes)], ['query']),
  'getQuestionPaperById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(QuestionPaper)],
      ['query'],
    ),
  'getQuestionPapersBySubject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(QuestionPaper)],
      ['query'],
    ),
  'getSemesters' : IDL.Func([], [IDL.Vec(Semester)], ['query']),
  'getSemestersByBranch' : IDL.Func([IDL.Nat], [IDL.Vec(Semester)], ['query']),
  'getSubject' : IDL.Func([IDL.Nat], [IDL.Opt(Subject)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getSubjectsBySemester' : IDL.Func([IDL.Nat], [IDL.Vec(Subject)], ['query']),
  'getSyllabusBySubject' : IDL.Func([IDL.Nat], [IDL.Opt(Syllabus)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'search' : IDL.Func([IDL.Text], [SearchResult], ['query']),
  'updateBranch' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateMCQ' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateNotes' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), ExternalBlob],
      [],
      [],
    ),
  'updateQuestionPaper' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text), ExternalBlob],
      [],
      [],
    ),
  'updateSemester' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updateSubject' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'updateSyllabus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MCQAnswer = IDL.Record({
    'mcqId' : IDL.Nat,
    'selectedAnswer' : IDL.Nat,
  });
  const MCQPracticeResult = IDL.Record({
    'score' : IDL.Float64,
    'totalQuestions' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
  });
  const Branch = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const MCQ = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'explanation' : IDL.Opt(IDL.Text),
    'correctAnswer' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Notes = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'year' : IDL.Nat,
    'subjectId' : IDL.Nat,
  });
  const QuestionPaper = IDL.Record({
    'id' : IDL.Nat,
    'file' : ExternalBlob,
    'year' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'examType' : IDL.Opt(IDL.Text),
  });
  const Semester = IDL.Record({
    'id' : IDL.Nat,
    'number' : IDL.Nat,
    'branchId' : IDL.Nat,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'semesterId' : IDL.Nat,
    'branchId' : IDL.Nat,
  });
  const Syllabus = IDL.Record({ 'overview' : IDL.Text, 'subjectId' : IDL.Nat });
  const SearchResult = IDL.Record({
    'questionPapers' : IDL.Vec(QuestionPaper),
    'subjects' : IDL.Vec(Subject),
    'mcqs' : IDL.Vec(MCQ),
    'notes' : IDL.Vec(Notes),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBranch' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addMCQ' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addNotes' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'addQuestionPaper' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text), ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'addSemester' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'addSubject' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addSyllabus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBranch' : IDL.Func([IDL.Nat], [], []),
    'deleteMCQ' : IDL.Func([IDL.Nat], [], []),
    'deleteNotes' : IDL.Func([IDL.Nat], [], []),
    'deleteQuestionPaper' : IDL.Func([IDL.Nat], [], []),
    'deleteSemester' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'deleteSyllabus' : IDL.Func([IDL.Nat], [], []),
    'evaluateMCQAnswers' : IDL.Func(
        [IDL.Vec(MCQAnswer)],
        [MCQPracticeResult],
        ['query'],
      ),
    'getBranch' : IDL.Func([IDL.Nat], [IDL.Opt(Branch)], ['query']),
    'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMCQById' : IDL.Func([IDL.Nat], [IDL.Opt(MCQ)], ['query']),
    'getMCQsBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(MCQ)], ['query']),
    'getNotesById' : IDL.Func([IDL.Nat], [IDL.Opt(Notes)], ['query']),
    'getNotesBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Notes)], ['query']),
    'getQuestionPaperById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(QuestionPaper)],
        ['query'],
      ),
    'getQuestionPapersBySubject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(QuestionPaper)],
        ['query'],
      ),
    'getSemesters' : IDL.Func([], [IDL.Vec(Semester)], ['query']),
    'getSemestersByBranch' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Semester)],
        ['query'],
      ),
    'getSubject' : IDL.Func([IDL.Nat], [IDL.Opt(Subject)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getSubjectsBySemester' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Subject)],
        ['query'],
      ),
    'getSyllabusBySubject' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Syllabus)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'search' : IDL.Func([IDL.Text], [SearchResult], ['query']),
    'updateBranch' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateMCQ' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateNotes' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), ExternalBlob],
        [],
        [],
      ),
    'updateQuestionPaper' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text), ExternalBlob],
        [],
        [],
      ),
    'updateSemester' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'updateSubject' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'updateSyllabus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };